name: Rubocop and Rspec 
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Boot RabbitMQ
        run: |
          sudo apt-get update
          sudo apt-get install rabbitmq-server
          sudo rabbitmqctl add_vhost event_source
          sudo rabbitmqctl set_permissions -p event_source guest ".*" ".*" ".*"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-event_source-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            ${{ runner.os }}-event_source-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
#      - name: Run rubocop
#        run: |
#          bundle exec rubocop
      - name: Run rspec
        run: |
          bundle exec rspec
